### ISSUE TITLE
Eglot mode-line is hard to read

### ISSUE THREAD

**Issue by jpe90** [smallwat3r/emacs-simplicity-theme#2]
[Eglot](https://github.com/joaotavora/eglot)'s mode-line information is currently hard to make out in active windows. See the far right text below:

![before_eglot](https://user-images.githubusercontent.com/9307830/195521220-0e247462-48b5-4d83-994c-1dec6a6cd412.png)

**Comment by smallwat3r** [comment]
Thanks for contributing to this repo @jpe90!

I will close this issue now, as I just merged https://github.com/smallwat3r/emacs-simplicity-theme/pull/3
